version: '3'

services:
  nodejs-fastify-solid-prisma-docker_pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=passDocker
      - POSTGRESQL_DATABASE=nodejs-fastify-solid-prisma-docker_pg